# Generated by Django 4.2.5 on 2026-04-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_hospital', models.CharField(default='MedAgenda Hospital', max_length=200)),
                ('logo_hospital', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('endereco', models.CharField(blank=True, max_length=300, null=True)),
                ('horario_manha', models.CharField(default='07:00', max_length=5)),
                ('horario_tarde', models.CharField(default='13:00', max_length=5)),
                ('horario_noite', models.CharField(default='19:00', max_length=5)),
                ('notificacoes_email', models.BooleanField(default=True)),
                ('notificacoes_whatsapp', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
    ]
